### ISSUE TITLE
Databricks to Notion

### ISSUE THREAD

**Issue by empiimp** [ayvi-0001/notion-api#1]
I'm trying to use notion-api within Databricks and get the following error when I try to install it:
%pip is a magic installation into the notebook

%pip install notion-api 

CalledProcessError                        Traceback (most recent call last)
<command-3627178215581541> in <module>
      1 #%pip install notion-client
      2 #%pip install notion-objects
----> 3 get_ipython().run_line_magic('pip', 'install notion-api')

/databricks/python/lib/python3.8/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2342                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2343             with self.builtin_trap:
-> 2344                 result = fn(*args, **kwargs)
   2345             return result
   2346 
/databricks/python/lib/python3.8/site-packages/decorator.py in fun(*args, **kw)
    229             if not kwsyntax:
    230                 args, kw = fix(args, kw, sig)
--> 231             return caller(func, *(extras + args), **kw)
    232     fun.__name__ = func.__name__
    233     fun.__doc__ = func.__doc__

/databricks/python/lib/python3.8/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/databricks/python_shell/dbruntime/PipMagicOverrides.py in pip(self, line)
     26     @line_magic
     27     def pip(self, line):
---> 28         self.pipMagicHandler.runCmd("pip", line)
     29 
     30 

/databricks/python_shell/dbruntime/PipMagicOverrides.py in runCmd(self, magicCmd, line)
     47             self.entry_point.restartInterpAfterExecution()
     48         if parsedResult.rewrittenCommand():
---> 49             self.executePipCommand(parsedResult)
     50         envManager.postExecute(parsedResult)
     51         if parsedResult.isMutation():

/databricks/python_shell/dbruntime/PipMagicOverrides.py in executePipCommand(self, result)
     98             sys.stdout.flush()
     99             if returncode != 0:
--> 100                 raise subprocess.CalledProcessError(returncode, origCmd)
    101         finally:
    102             end = time.time()

CalledProcessError: Command 'pip --disable-pip-version-check install notion-api' returned non-zero exit status 1.

**Comment by ayvi-0001** [comment]
I believe this has to do with the python version being used. It says you are using python3.8
I tried running a script on 3.8 using the same pip install line as in your error:

![1680308499](https://user-images.githubusercontent.com/101922566/229257060-f964ac1f-e4da-4f3b-9075-aacc29baaaf8.png)


The library requires Python >=3.10. This was only noted in the project meta on PyPI, so I'm adding a badge at the top of the README now to clear any confusion.
